export enum POSTALCODE_REGEX {
    AC = "^[Aa][Ss][Cc][Nn]\\s{0,1}[1][Zz][Zz]$", // Ascension island
    AD = "^AD\\d{3}$", // Andorra
    AF = "^\\d{4}$", // Afghanistan
    AG = "", // Antigua and Barbuda
    AI = "^[Aa][I][-][2][6][4][0]$", // Anguilla
    AL = "^\\d{4}$", // Albania
    AM = "^\\d{4}$", // Armenia
    AO = "", // Angola
    AR = "^\\d{4}|[A-Z]\\d{4}[A-Z]{3}$", // Argentina
    AS = "^\\d{5}$", // American Samoa
    AT = "^\\d{4}$", // Austria
    AU = "^\\d{4}$", // Australia
    AW = "", // Aruba
    AX = "^\\d{5}$", // Åland Islands
    AZ = "^[Aa][Zz]\\d{4}$", // Azerbaijan
    BA = "^\\d{5}$", // Bosnia and Herzegovina
    BB = "^[Aa][Zz]\\d{5}$",
    BD = "^\\d{4}$", // Bangladesh
    BE = "^\\d{4}$", // Belgium
    BF = "", // Burkina Faso
    BG = "^\\d{4}$", // Bulgaria
    BH = "^\\d{3,4}$", // Bahrain
    BI = "", // Burundi
    BJ = "", // Benin
    BM = "^[A-Za-z]{2}\\s([A-Za-z]{2}|\\d{2})$", // Bermuda
    BN = "^[A-Za-z]{2}\\d{4}$", // Brunei
    BO = "^\\d{4}$", // Bolivia
    BQ = "", // Bonaire, Sint Eustatius and Saba
    BR = "^\\d{5}-?\\d{3}$", // Brazil
    BS = "", // Bahamas
    BT = "^\\d{5}$", // Bhutan
    BW = "", // Botswana
    BY = "^\\d{6}$", // Belarus
    BZ = "", // Belize
    CA = "^(?=[^DdFfIiOoQqUu\\d\\s])[A-Za-z]\\d(?=[^DdFfIiOoQqUu\\d\\s])[A-Za-z]\\s{0,1}\\d(?=[^DdFfIiOoQqUu\\d\\s])[A-Za-z]\\d$", // Canada
    CC = "^\\d{4}$", // Cocos (Keeling) Island
    CD = "^[Cc][Dd]$", // Congo, Democratic Republic
    CF = "", // Central African Republic
    CG = "", // Congo (Brazzaville)
    CH = "^\\d{4}$", // Switzerland
    CK = "", // Cook Islands
    CL = "^\\d{7}\\s\\(\\d{3}-\\d{4}\\)$", // Chile
    CM = "", // Cameroon
    CN = "^\\d{6}$", // China
    CO = "^\\d{6}$", // Colombia
    CR = "^\\d{4,5}$", // Costa Rica
    CS = "^\\d{5}$", // Serbia and Montenegro
    CU = "^\\d{5}$", // Cuba
    CV = "^\\d{4}$", // Cape Verde
    CW = "", // Curaçao
    CX = "^\\d{4}$", // Christmas Island
    CY = "^\\d{4}$", // Cyprus
    CZ = "^\\d{5}\\s\\(\\d{3}\\s\\d{2}\\)$", // Czech Republic
    DE = "^\d{2}$|^\d{4}$|^\d{5}$", // Germany
    DJ = "", // Djibouti
    DK = "^\\d{4}$", // Denmark
    DM = "", // Dominica
    DO = "^\\d{5}$", // Dominican Republic
    DZ = "^\\d{5}$", // Algeria
    EC = "^\\d{6}$", // Ecuador
    EE = "^\\d{5}$", // Estonia
    EG = "^\\d{5}$", // Egypt
    ER = "", // Eritrea
    ES = "^\\d{5}$", // Spain
    ET = "^\\d{4}$", // Ethiopia
    FI = "^\\d{5}$", // Finland
    FJ = "", // Fiji
    FK = "^[Ff][Ii][Qq]{2}\\s{0,1}[1][Zz]{2}$", // Falkland Islands
    FM = "^\\d{5}$", // Micronesia
    FO = "^\\d{3}$", // Faroe Islands
    FR = "^\\d{5}$", // France
    GA = "^\\d{2}\\s[a-zA-Z-_ ]\\s\\d{2}$", // Gabon
    GB = "^(GIR 0AA|[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2})$", // United Kingdom
    GD = "", // Grenada
    GE = "^\\d{4}$", // Georgia
    GF = "^973\\d{2}$", // French Guiana
    GH = "", // Ghana
    GI = "^[Gg][Xx][1]{2}\\s{0,1}[1][Aa]{2}$", // Gibraltar
    GG = "^GY\\d{1,2} \\d[A-Z]{2}$", // Guernsey
    GL = "^39\\d{2}$", // Greenland
    GM = "", // Gambia
    GN = "", // Guinea
    GP = "^971\\d{2}$", // Guadeloupe
    GQ = "", // Equatorial Guinea
    GR = "^\\d{3}\\s{0,1}\\d{2}$", // Greece
    GT = "^\\d{5}$", // Guatemala
    GU = "^969\\d{2}$", // Guam
    GW = "^\\d{4}", // Guinea Bissau
    GY = "", // Guyana
    HK = "", // Hong Kong
    HN = "^\\d{5}$", // Honduras
    HR = "^\\d{5}$", // Croatia
    HT = "^\\d{4}$", // Haiti
    HU = "^\\d{4}$", // Hungary
    ID = "^\\d{5}$", // Indonesia
    IE = "^[A-Z0-9]{3,4} [A-Z0-9]{4}$", // Ireland
    IL = "^\\d{5,7}$", // Israel
    IN = "^\\d{6}$", // India
    IO = "^[Bb]{2}[Nn][Dd]\\s{0,1}[1][Zz]{2}$", // British Indian Ocean Territory
    IQ = "^\\d{5}$", // Iraq
    IR = "^\\d{5}-\\d{5}$", // Iran
    IS = "^\\d{3}$", // Iceland
    IT = "^\\d{5}$", // Italy
    JE = "^JE\\d{1,2} \\d[A-Z]{2}$", // Jersey
    JM = "^\\d{2}$", // Jamaica
    JP = "^\\d{3}-\\d{4}$", // Japan
    KE = "^\\d{5}$", // Kenya
    KG = "^\\d{6}$", // Kyrgyzstan
    KH = "^\\d{5}$", // Cambodia
    KM = "", // Comoros
    KR = "^\\d{5}$", // South Korea
    KW = "^\\d{5}$", // Kuwait
    KY = "^[Kk][Yy]\\d[-\\s]{0,1}\\d{4}$", // Cayman Islands
    KZ = "^\\d{6}$", // Kazakhstan
    LA = "^\\d{5}$", // Laos
    LB = "^\\d{4}( \\d{4})?$", // Lebanon
    LI = "^\\d{4}$", // Liechtenstein
    LK = "^\\d{5}$", // Sri Lanka
    LT = "^LT-\\d{5}$", // Lithuania
    LU = "^L-\\d{4}$", // Luxembourg
    LV = "^LV-\\d{4}$", // Latvia
    MA = "^\\d{5}$", // Morocco
    MC = "^980\\d{2}$", // Monaco
    MD = "^MD-\\d{4}$", // Moldova
    ME = "^\\d{5}$", // Montenegro
    MG = "^\\d{3}$", // Madagascar
    MK = "^\\d{4}$", // North Macedonia
    MN = "^\\d{5}$", // Mongolia
    MT = "^[A-Z]{3} \\d{4}$", // Malta
    MX = "^\\d{5}$", // Mexico
    MY = "^\\d{5}$", // Malaysia
    NG = "^\\d{6}$", // Nigeria
    NL = "^\\d{4} [A-Z]{2}$", // Netherlands
    NO = "^\\d{4}$", // Norway
    NP = "^\\d{5}$", // Nepal
    NZ = "^\\d{4}$", // New Zealand
    OM = "^\\d{3}$", // Oman
    PE = "^\\d{5}$", // Peru
    PF = "^987\\d{2}$", // French Polynesia
    PH = "^\\d{4}$", // Philippines
    PK = "^\\d{5}$", // Pakistan
    PL = "^\\d{2}-\\d{3}$", // Poland
    PT = "^\\d{4}-\\d{3}$", // Portugal
    RE = "^974\\d{2}$", // Réunion
    RO = "^\\d{6}$", // Romania
    RS = "^\\d{5}$", // Serbia
    RU = "^\\d{6}$", // Russia
    SA = "^\\d{5}-\\d{4}$", // Saudi Arabia
    SE = "^\\d{3} \\d{2}$", // Sweden
    SG = "^\\d{6}$", // Singapore
    SK = "^\\d{3} \\d{2}$", // Slovakia
    SM = "^4789\\d$", // San Marino
    SV = "^1101$", // El Salvador
    TD = "^\\d{5}$", // Chad
    TF = "", // French Southern and Antarctic Territories
    TH = "^\\d{5}$", // Thailand
    TR = "^\\d{5}$", // Turkey
    TW = "^\\d{3,5}$", // Taiwan
    UA = "^\\d{5}$", // Ukraine
    UK = "^(GIR 0AA|[A-Z]{1,2}\\d[A-Z\\d]? ?\\d[A-Z]{2})$", // United Kingdom
    US = "^\\d{5}(-\\d{4})?$", // United States
    UY = "^\\d{5}$", // Uruguay
    UZ = "^\\d{6}$", // Uzbekistan
    VG = "^[Vv][Gg]\\d{4}$", // British Virgin Islands
    VN = "^\\d{6}$", // Vietnam
    ZA = "^\\d{4}$", // South Africa
    ZM = "^\\d{5}$", // Zambia
    ZW = "^\\d{4}$", // Zimbabwe
}
